### PR TITLE
Fix iOS errors

### PR DESCRIPTION
**Pull request by izambasiron**
Had to rename montserratBold file, see here http://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/#findfontname

### CODE REVIEW

**Comment by satya164** [comment]
Thank you. Unfortunately I checked it out and tried to build it. But getting this error. Any idea?

image

**Comment by izambasiron** [comment]
No worries. Have you tried this https://github.com/facebook/react-native/issues/12042#issuecomment-275025960

screen shot 2017-02-19 at 8 06 40 am

For me, I had an error for `React/RCTEventEmitter.h`. I had to only build `React`, skipping step 3.

**Comment by satya164** [comment]
@izambasiron thanks, trying now

**Comment by satya164** [comment]
That worked. Thanks a lot.

**Pull request merged**
